# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

local:
  secret_key_base: b23b77f2a34a0b452bbd4128b788e613f74a768c2dfa25ccb914411667384ce6a53ca9e3dfddc3024e511f9f3e2b3d76fc3dac5515c3deb36d187b4d00e93991

test:
  secret_key_base: edd6ed643d189eb9840081e38ad2216552677185d47ec2ff2ec6239ad0b14fe5f2b30724091538254a1055a16b1043f2fb465c37b5eb2a872af3ca667b8660e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
